import '@/styles/globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import { ChakraProvider } from '@chakra-ui/react'
import { extendTheme } from "@chakra-ui/react"
import Head from 'next/head'


const theme = extendTheme({
  styles: {
    global: {
      body: {
        bg:"#011627",
        color: "#607B96",
        fontFamily: "Fira Code",
      },
    },
  },
})
export default function App({ Component, pageProps }) {
  return(
    <>
    <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
@import url('https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;500&display=swap');
</style>
    </Head>
    <ChakraProvider
    theme={theme} 
    >
      <Header />
      <div
       style={{
        marginTop:"60px"

       }}
      >
      <Component {...pageProps} />
      </div>
      <Footer />
      </ChakraProvider>
    </>
  )
}
